// vue-vite-ts-tailwind/src/components/pages/users/UsersPage.vue
<script setup lang="ts">
import services from '@/services';
import { useQuery } from '@tanstack/vue-query';
import { reactive, watch } from 'vue';

const page = reactive({
  page: 0,
  size: 10,
});

// Queries
const { data: userData, isError } = useQuery({
  queryKey: ['users', page],
  queryFn: async () => {
    const res = await services.product.getListUser({
      page: page.size,
      size: page.page,
    });
    return res?.data;
  },
  retry: 1,
});

watch(isError, () => {
  if (isError) {
    alert('Something went wrong');
  }
});
</script>

<template>
  <div v-for="user in userData" :key="user.id">
    {{ user.username }}
  </div>
</template>

// reactjs-ts-vite-antd/src/components/pages/user/UsersPage.tsx
import { UserData } from '@/lib/types/productTypes';
import services from '@/services';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

function UsersPage() {
  const queryClient = useQueryClient();

  const [page, setPage] = useState({ page: 0, size: 10 });

  const { data: userData } = useQuery({
    queryKey: ['users', page],
    queryFn: async () => {
      const res = await services.product.getListUser({
        page: page.size,
        size: page.page,
      });
      return res?.data;
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await services.product.deleteUser(id); // Replace with actual delete function
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['users'] });
    },
  });

  const handleChangePage = (page: { page: number; size: number }) => {
    setPage(page);
  };

  return (
    <>
      <button onClick={() => handleChangePage({ page: page.page - 1, size: page.size })}>
        prev
      </button>
      <button onClick={() => handleChangePage({ page: page.page + 1, size: page.size })}>
        next
      </button>

      <ul>
        {userData?.map((user: UserData) => (
          <li key={user.id}>
            <span className="mr-2">{user.username}</span>
            <button onClick={() => deleteMutation.mutate(user.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </>
  );
}

export default UsersPage;
