// reactjs-ts-vite-antd/src/components/pages/auth/LoginPage.tsx
import { LoginData } from '@/lib/types/authTypes';
import services from '@/services';
import { setAuthenticate } from '@/store/reducer/AuthReducer';
import { useMutation } from '@tanstack/react-query';
import { Button, Form, Input } from 'antd';
import { get } from 'lodash';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';

const formItemLayout = {
  labelCol: {
    xs: { span: 24 },
    sm: { span: 8 },
  },
  wrapperCol: {
    xs: { span: 24 },
    sm: { span: 16 },
  },
};

const LoginPage = () => {
  const [form] = Form.useForm();

  const navigate = useNavigate();
  const dispatch = useDispatch();

  // Mutations
  const handleLogin = useMutation({
    mutationFn: (data: LoginData) => {
      return services.auth.handleLogin(data);
    },
  });

  function onSubmit(data: LoginData) {
    handleLogin.mutate(data, {
      onError: error => {
        // An error happened!
        const message = get(error, 'data.message', 'Something went wrong');
        console.error('Login error:', message);
      },
      onSuccess: res => {
        const data = { ...get(res, 'data', {}), isAuthenticated: true };
        dispatch(setAuthenticate(data));
        console.log('Login success', data);
        navigate('/');
      },
    });
  }

  return (
    <>
      <div className="font-bold">Login Page</div>
      <Form
        {...formItemLayout}
        form={form}
        name="register"
        onFinish={onSubmit}
        initialValues={{ username: 'test' }}
        style={{ maxWidth: 600 }}
        scrollToFirstError
      >
        <Form.Item
          name="username"
          label="Username"
          rules={[
            {
              required: true,
              message: 'Please input your Username!',
            },
          ]}
        >
          <Input />
        </Form.Item>

        <Form.Item
          name="password"
          label="Password"
          rules={[
            {
              required: true,
              message: 'Please input your password!',
            },
          ]}
          hasFeedback
        >
          <Input.Password />
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit">
            Register
          </Button>
        </Form.Item>
      </Form>
    </>
  );
};

export default LoginPage;

// vue-vite-ts-tailwind/src/components/pages/auth/LoginPage.vue
<script setup lang="ts">
import router from '@/routes';
import services from '@/services';
import { useAuthStore } from '@/stores/auth';
import type { AuthData } from '@/utils/types/authTypes';
import { useMutation } from '@tanstack/vue-query';
import { get } from 'lodash';
import { reactive } from 'vue';

// Stores
const authStore = useAuthStore();

const formState = reactive({
  username: '',
  password: '',
});

// Mutations
const handleLogin = useMutation({
  mutationFn: (data: AuthData) => {
    return services.auth.handleLogin(data);
  },
});

// Functions
function onSubmit() {
  const data: AuthData = {
    username: formState.username,
    password: formState.password,
  };

  handleLogin.mutate(data, {
    onError: error => {
      // An error happened!
      const message = get(error, 'data.message', 'Something went wrong');
      alert(`Login failed: ${message}`);
    },
    onSuccess: res => {
      const data = { ...get(res, 'data', {}), isAuthenticated: true };
      authStore.setAuthenticated(data);
      router.push('/');
    },
  });
}
</script>

<template>
  <div class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
    <div>isAuthencatided: {{ authStore.userInfo.isAuthenticated ? 'yes' : 'no' }}</div>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="#" method="POST">
        <div>
          <label for="email" class="block text-sm/6 font-medium text-gray-900">Username</label>
          <div class="mt-2">
            <input
              v-model="formState.username"
              type="text"
              name="username"
              class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
            />
          </div>
        </div>

        <div>
          <div class="flex items-center justify-between">
            <label for="password" class="block text-sm/6 font-medium text-gray-900">Password</label>
          </div>
          <div class="mt-2">
            <input
              v-model="formState.password"
              type="password"
              name="password"
              class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
            />
          </div>
        </div>

        <div>
          <button
            @click.prevent="onSubmit"
            type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Sign in
          </button>
        </div>
      </form>

      <p class="mt-10 text-center text-sm/6 text-gray-500">
        Not a member?
        {{ ' ' }}
        <RouterLink to="/auth/register" class="font-semibold text-indigo-600 hover:text-indigo-500"
          >Register now</RouterLink
        >
      </p>
    </div>
  </div>
</template>
