// reactjs-ts-vite-shadcn/src/components/pages/auth/LoginPage.tsx
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import services from '@/services';
import { setAuthenticate } from '@/store/reducer/AuthReducer';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation } from '@tanstack/react-query';
import { get } from 'lodash';
import { useForm } from 'react-hook-form';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { z } from 'zod';

const FormSchema = z.object({
  username: z.string().min(2, {
    message: 'Username must be at least 2 characters.',
  }),
  password: z.string().min(6, {
    message: 'Password must be at least 6 characters.',
  }),
});

const LoginPage = () => {
  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      username: '',
    },
  });
  const navigate = useNavigate();
  const dispatch = useDispatch();

  // Mutations
  const handleLogin = useMutation({
    mutationFn: (data: z.infer<typeof FormSchema>) => {
      return services.auth.handleLogin(data);
    },
  });

  function onSubmit(data: z.infer<typeof FormSchema>) {
    handleLogin.mutate(data, {
      onError: error => {
        // An error happened!
        const message = get(error, 'data.message', 'Something went wrong');
        toast.success(`Login failed: ${message}`);
      },
      onSuccess: res => {
        const data = { ...get(res, 'data', {}), isAuthenticated: true };
        dispatch(setAuthenticate(data));
        toast.success('Login successful');
        navigate('/');
      },
    });
  }

  return (
    <>
      <div className="font-bold">Login Page</div>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="w-2/3 space-y-6">
          <FormField
            control={form.control}
            name="username"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Username</FormLabel>
                <FormControl>
                  <Input placeholder="shadcn" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <Input type="password" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button type="submit">Submit</Button>
        </form>
      </Form>
    </>
  );
};

export default LoginPage;

// vue-vite-ts-tailwind/src/components/pages/auth/LoginPage.vue
<script setup lang="ts">
import router from '@/routes';
import services from '@/services';
import { useAuthStore } from '@/stores/auth';
import type { AuthData } from '@/utils/types/authTypes';
import { useMutation } from '@tanstack/vue-query';
import { get } from 'lodash';
import { reactive } from 'vue';

// Stores
const authStore = useAuthStore();

const formState = reactive({
  username: '',
  password: '',
});

// Mutations
const handleLogin = useMutation({
  mutationFn: (data: AuthData) => {
    return services.auth.handleLogin(data);
  },
});

// Functions
function onSubmit() {
  const data: AuthData = {
    username: formState.username,
    password: formState.password,
  };

  handleLogin.mutate(data, {
    onError: error => {
      // An error happened!
      const message = get(error, 'data.message', 'Something went wrong');
      alert(`Login failed: ${message}`);
    },
    onSuccess: res => {
      const data = { ...get(res, 'data', {}), isAuthenticated: true };
      authStore.setAuthenticated(data);
      router.push('/');
    },
  });
}
</script>

<template>
  <div class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
    <div>isAuthencatided: {{ authStore.userInfo.isAuthenticated ? 'yes' : 'no' }}</div>
    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
      <form class="space-y-6" action="#" method="POST">
        <div>
          <label for="email" class="block text-sm/6 font-medium text-gray-900">Username</label>
          <div class="mt-2">
            <input
              v-model="formState.username"
              type="text"
              name="username"
              class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
            />
          </div>
        </div>

        <div>
          <div class="flex items-center justify-between">
            <label for="password" class="block text-sm/6 font-medium text-gray-900">Password</label>
          </div>
          <div class="mt-2">
            <input
              v-model="formState.password"
              type="password"
              name="password"
              class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
            />
          </div>
        </div>

        <div>
          <button
            @click.prevent="onSubmit"
            type="submit"
            class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Sign in
          </button>
        </div>
      </form>

      <p class="mt-10 text-center text-sm/6 text-gray-500">
        Not a member?
        {{ ' ' }}
        <RouterLink to="/auth/register" class="font-semibold text-indigo-600 hover:text-indigo-500"
          >Register now</RouterLink
        >
      </p>
    </div>
  </div>
</template>
